### ISSUE TITLE
Minitouch obsolete?

### ISSUE THREAD

**Issue by stoefln** [DeviceFarmer/minitouch#5]
I have found out that touches can also be sent via ADB.
https://adbinstaller.com/commands/adb-shell-input-tap-5b67dc5ee7958178a295553f

Am I correct about my assumption that this would render minitouch obsolete?

**Comment by stoefln** [comment]
@koral-- maybe?

**Comment by bchanot** [comment]
the adb command for tap exist since a long time. but it cannot handle multi-touch gesture.

**Comment by stoefln** [comment]
@bchanot thank you!
